version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=60
